apiVersion: apps/v1
kind: Deployment
metadata: 
  name: devlop
spec:
  selector:
    matchLabels:
      app: devlop
  replicas: 2 
  template:
    metadata:
      labels:
        app: devlop
    spec:
      containers:
        - name: devlop
          image: prashantshivach/image:22
        
          ports:
            - containerPort: 8000 


---

apiVersion: v1 
kind: Service 
metadata: 
  name: devlop
spec:
  selector:
    app: devlop
  ports:
    - protocol: "TCP"
      port: 4001
      nodePort: 32500
      targetPort: 8000
  type: NodePort 
